# Generated by Django 5.0.7 on 2024-07-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=15)),
                ('user', models.CharField(db_column='phoneNumber', max_length=20, verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('four_digit_code', models.CharField(default='0000', max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
